### ISSUE TITLE
Improve Swagger UI

### ISSUE THREAD

**Issue by thesayfulla** [ildiz/ildiz#5]
### My yaml file:
```yaml
person:
  id: INTEGER PRIMARY KEY
  name: TEXT
  age: INTEGER

contact:
  id: INTEGER PRIMARY KEY
  email: TEXT
```

### Generated Swagger UI:
![image](https://github.com/ildiz/ildiz/assets/61648680/0d47b38b-eba2-40a9-bff3-3185cabe3783)

### Expected Swagger UI:
![image](https://github.com/ildiz/ildiz/assets/61648680/dc0d2645-3530-4396-9c23-23f792adf053)
